version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: laravel-app
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    networks:
      backend:
        aliases:
          - laravel-app

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
      - ./sql:/tmp/sql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=jigsaw
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    ports:
      - 33060:3306
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network
